# Generated by Django 3.1.4 on 2021-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_staff_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='passport',
            field=models.ImageField(blank=True, upload_to='staff/passports/'),
        ),
    ]
