# Generated by Django 3.1.4 on 2021-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_staff_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='passport',
            field=models.ImageField(blank=True, upload_to='passports/'),
        ),
    ]
