# Generated by Django 3.1.4 on 2021-05-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210511_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
